### ISSUE TITLE
Investigate ARDB replication

### ISSUE THREAD

**Issue by grimpy** [g8os/home#28] opened 2017-04-18 09:34 UTC
Standard ARDB configuration does not allowe a slave to do full replication if master has several gigabytes of data and slave has to catchup.
This is based on tests I've run myself.
Please validate and find a fix.

**Comment by iwanbk** [comment] 2017-04-18 11:52
@grimpy can you provide steps to reproduce it?

**Comment by maxux** [comment] 2017-04-18 13:16
You can easily reproduce it by filling an ardb server with a lot of values (go to up 2 GB of data), then connect a slave to it. Slave will not sync correctly.

**Comment by iwanbk** [comment] 2017-04-19 06:30
I did 3 test scenarios:

test 1:
- start ardb master
- start ardb slave
- fill 2GB of data to master
-  test read data from slave : OK (need to wait for several seconds)

we need to change `repl-backlog-size` config from 1G to 5G, otherwise it failed after 1GB

test 2:
- start redis-2.3 master
- fill 2GB of data
- start ardb slave
- test read data from slave : OK

test 3:
- start ardb master
- fill few MB of data
- start ardb slave
- test read data from slave : failed

i checked the slave's log for both test 2 and test 3, and there is  a difference:
- in test 2, with redis master, slave do FULLRESYNC
- in test 3, with ardb master, slave do FULLBACKUP

full log of test 2
```
$ ./ardb-server ./ardb-slave.conf 
[12566] 04-19 11:52:55,153 INFO Success to open lmdb at /home/ibk/work/g8os/ardb-replication/slave/data/lmdb
[12566] 04-19 11:52:55,153 INFO Ardb init engine:lmdb success.
[12566] 04-19 11:52:55,155 INFO Ardb will accept connections on 0.0.0.0:6380
[12566] 04-19 11:52:55,156 INFO Ardb started with version 0.9.4
[12566] 04-19 11:53:25,178 INFO [Slave]Connecting master 127.0.0.1:6379
[12566] 04-19 11:53:25,179 INFO [Slave]Remote master is a Redis 3.0.6 instance, support partial sync:1
[12566] 04-19 11:53:25,179 INFO Send psync ? 0
[12566] 04-19 11:53:25,188 INFO Recv psync reply:FULLRESYNC 679ce79021af337eb513d2fcc8d7ccc945659771 1
[12566] 04-19 11:53:26,815 INFO [Slave]Create dump file:/home/ibk/work/g8os/ardb-replication/slave/backup/sync-redis-snapshot.1.0.1492577606, expected size:22763892, master is redis:1
[12566] 04-19 11:53:26,913 INFO Start loading snapshot:/home/ibk/work/g8os/ardb-replication/slave/backup/sync-redis-snapshot.1.0.1492577606
[12566] 04-19 11:53:28,988 INFO 10482787 bytes loaded from dump file.
[12566] 04-19 11:53:33,304 INFO 20965546 bytes loaded from dump file.
[12566] 04-19 11:53:35,073 INFO All data load successfully from redis snapshot file.
[12566] 04-19 11:53:35,073 INFO Redis snapshot file load finished.
[12566] 04-19 11:53:35,073 INFO Cost 8.16s to load snapshot file with type:redis.
[12566] 04-19 11:53:35,073 INFO Start to replay wal from sync offset:1 & wal end offset:15
[12566] 04-19 11:53:35,073 INFO Complete replay wal with sync offset:15 & wal end offset:15
[12566] 04-19 11:53:35,074 INFO Add cached snapshot:sync-redis-snapshot.1.0.1492577606
[12566] 04-19 11:53:35,188 WARN Remove snapshot:/home/ibk/work/g8os/ardb-replication/slave/backup/sync-redis-snapshot.1.0.1492577606 since it's too old.
[12566] 04-19 11:53:35,188 WARN Remove snapshot file:/home/ibk/work/g8os/ardb-replication/slave/backup/sync-redis-snapshot.1.0.1492577606
```

full log of test 3
```
$ ./ardb-server ./ardb-slave.conf 
[12463] 04-19 11:50:57,618 INFO Success to open lmdb at /home/ibk/work/g8os/ardb-replication/slave/data/lmdb
[12463] 04-19 11:50:57,618 INFO Ardb init engine:lmdb success.
[12463] 04-19 11:50:57,620 INFO Ardb will accept connections on 0.0.0.0:6380
[12463] 04-19 11:50:57,621 INFO Ardb started with version 0.9.4
[12463] 04-19 11:51:26,642 INFO [Slave]Connecting master 127.0.0.1:6379
[12463] 04-19 11:51:26,642 INFO [Slave]Remote master is an ardb instance.
[12463] 04-19 11:51:26,643 INFO Send psync ? 0 cksm 0 engine lmdb
[12463] 04-19 11:51:26,644 INFO Recv psync reply:FULLBACKUP 27e144afe5568d89b788875089a0ed0c1a7d5816 200006713 12737470374050599689
[12463] 04-19 11:51:26,644 INFO [Slave]Create sync backup path:/home/ibk/work/g8os/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492577486.tmp
[12463] 04-19 11:51:30,081 INFO Backup file:data.mdb sync success.
[12463] 04-19 11:51:30,081 INFO Backup sync success.
[12463] 04-19 11:51:30,081 INFO Start loading snapshot:/home/ibk/work/g8os/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492577486
[12463] 04-19 11:51:30,083 INFO Success to open lmdb at /home/ibk/work/g8os/ardb-replication/slave/data/lmdb
[12463] 04-19 11:51:30,182 INFO Backup restore finished.
[12463] 04-19 11:51:30,182 INFO Cost 0.10s to load snapshot file with type:backup.
[12463] 04-19 11:51:30,182 INFO Start to replay wal from sync offset:200006713 & wal end offset:200006727
[12463] 04-19 11:51:30,182 INFO Complete replay wal with sync offset:200006727 & wal end offset:200006727
[12463] 04-19 11:51:30,182 INFO Add cached snapshot:sync-lmdb-backup.200006713.12737470374050599689.1492577486
[12463] 04-19 11:51:30,644 WARN Remove snapshot:/home/ibk/work/g8os/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492577486 since it's too old.
[12463] 04-19 11:51:30,644 WARN Remove snapshot file:/home/ibk/work/g8os/ardb-replication/slave/backup/sync-lmdb-backup.200006713.12737470374050599689.1492577486
```

**Comment by iwanbk** [comment] 2017-04-19 07:22
i modified ardb source code to make the slave also do `FULLRESYNC`, it still failed.

**Comment by iwanbk** [comment] 2017-04-20 04:13
i was using lmdb engine because rocksdb failed to built in my ubuntu 16.04 desktop.
But it built without issue in ubuntu 16.04 docker, strange.

rocksdb engine give me more info about the error
```
ERROR Failed to backup rocksdb for reason:NotFound: /root/repl-ardb/slave/backup/sync-rocksdb-backup.200006713.12737470374050599689.1492661173/meta is missing
```

Full log
```
[18673] 04-20 04:05:57,126 INFO [RocksDB]DB pointer 0x7f65363fb000
[18673] 04-20 04:05:57,127 INFO Ardb init engine:rocksdb success.
[18673] 04-20 04:05:57,129 INFO Ardb will accept connections on 0.0.0.0:6380
[18673] 04-20 04:05:57,130 INFO Ardb started with version 0.9.4
[18673] 04-20 04:06:13,138 INFO [Slave]Connecting master 127.0.0.1:6379
[18673] 04-20 04:06:13,138 INFO [Slave]Remote master is an ardb instance.
[18673] 04-20 04:06:13,138 INFO Send psync ? 0 cksm 0 engine rocksdb
[18673] 04-20 04:06:13,140 INFO Recv psync reply:FULLBACKUP 2c3f40ea78fb268fadcebe8bc868211761896405 200006713 12737470374050599689
[18673] 04-20 04:06:13,140 INFO [Slave]Create sync backup path:/root/repl-ardb/slave/backup/sync-rocksdb-backup.200006713.12737470374050599689.1492661173.tmp
[18673] 04-20 04:06:21,450 INFO Backup file: sync success.
[18673] 04-20 04:06:21,450 INFO Backup sync success.
[18673] 04-20 04:06:21,450 INFO Start loading snapshot:/root/repl-ardb/slave/backup/sync-rocksdb-backup.200006713.12737470374050599689.1492661173
[18673] 04-20 04:06:21,451 ERROR Failed to backup rocksdb for reason:NotFound: /root/repl-ardb/slave/backup/sync-rocksdb-backup.200006713.12737470374050599689.1492661173/meta is missing
[18673] 04-20 04:06:21,452 INFO [RocksDB]RocksDB version: 5.0.2
```

**Comment by iwanbk** [comment] 2017-04-20 10:20
the developer said that the issue has been fixed in rocksdb and lmdb https://github.com/yinqiwen/ardb/issues/332#issuecomment-295610628

Unfortunately it still failed for me when i use lmdb.

rocksdb failed to build, even in the docker.
Can someone here check if that fixes work for rocksdb?

**Comment by iwanbk** [comment] 2017-04-20 13:49
I managed to compile the rocksdb version, but slave still failed to sync with same error message (meta is missing)

**Comment by iwanbk** [comment] 2017-04-21 07:13
it is working now. please verify.

my tests:
- start ardb master
- fill ardb master with 20K of 100 KB  of data -> 2.X GB
- start ardb slave
- test read from slave: OK.

```
I managed to compile the rocksdb version, but slave still failed to sync with same error message (meta is missing)
```
i just re-run the test on fresh VPS, and it just worked fine.
previous test was done in docker.

**Closed** 2017-05-10 09:09 UTC
Labels: state_verification
